import {describe,it,expect} from 'vitest';
import {createCashAssumptionDataset,defaultCashPeriod,isCashOnly,parseMarketCsv} from '../src/data';
import {computeReview} from '../src/engine';
import {validateRecord,exportRecord} from '../src/records';
import type {ReviewSpec,ReviewRecord} from '../src/types';
const portfolio={id:'a',name:'Cash',holdings:[{symbol:'CASH',weight:1}]};
const spec=():ReviewSpec=>({a:structuredClone(portfolio),b:{...structuredClone(portfolio),id:'b'},dataset:createCashAssumptionDataset('2023-01-03','2025-01-03'),frequency:'monthly',costBps:20,initialNav:10000,cashReturnConfirmed:true,partialCoverageConfirmed:false});
describe('reachable cash assumption workflow',()=>{
 it('constructs a calendar-only dataset and produces a constant ledger',()=>{const s=spec(),r=computeReview(s);expect(s.dataset.symbols).toEqual([]);expect(s.dataset.prices.every(row=>row.length===0)).toBe(true);expect(r.symbols).toEqual(['CASH']);expect(new Set(r.history.a.nav)).toEqual(new Set([10000]));expect(r.history.a.fees).toBe(0);expect(r.history.a.turnover).toBe(0);expect(r.risk.windows[0].a?.relativeContributions).toBeNull();expect(r.warnings.join(' ')).not.toMatch(/Ledoit|Initial purchase fees/);});
 it('cannot turn mixed or unsupported portfolios into a cash shortcut',()=>{const s=spec();s.a.holdings=[{symbol:'CASH',weight:.5},{symbol:'UNKNOWN',weight:.5}];s.partialCoverageConfirmed=true;expect(isCashOnly(s.a,s.b)).toBe(false);expect(()=>computeReview(s)).toThrow(/entirely cash/);});
 it('rejects counterfeit market columns and requires confirmation',()=>{const s=spec();s.dataset.symbols=['SPY'];s.dataset.prices=s.dataset.dates.map(()=>[100]);expect(()=>computeReview(s)).toThrow(/cash/);const other=spec();other.cashReturnConfirmed=false;expect(()=>computeReview(other)).toThrow(/Confirm/);});
 it('bounds date range, future dates and minimum window',()=>{expect(()=>createCashAssumptionDataset('2025-01-02','2025-02-03')).toThrow(/253/);expect(()=>createCashAssumptionDataset('2015-01-02','2025-02-03')).toThrow(/five/);expect(()=>createCashAssumptionDataset('2025-01-02','2099-01-01')).toThrow(/today/);expect(defaultCashPeriod('2026-10-06')).toEqual({start:expect.any(String),end:'2026-10-05'});});
 it('cash is not an available user market CSV price basis',()=>{expect(()=>parseMarketCsv('date,SPY\n2023-01-03,100',{format:'wide',manifest:spec().dataset.manifest})).toThrow(/Cash assumptions/);});
 it('round trips v2 and still validates v1 historical snapshots',()=>{const s=spec(),r=computeReview(s);const record:ReviewRecord={schemaVersion:2,id:r.id,createdAt:new Date().toISOString(),rationale:'现金配置，等待下次复查。',nextReview:'2027-01-02',a:s.a,b:s.b,manifest:s.dataset.manifest,result:r,settings:{frequency:s.frequency,costBps:s.costBps,initialNav:s.initialNav,cashReturnConfirmed:true,partialCoverageConfirmed:false},dataset:s.dataset};expect(validateRecord(JSON.parse(exportRecord(record,true))).schemaVersion).toBe(2);expect(validateRecord({...record,schemaVersion:1}).schemaVersion).toBe(1);});
 it('retention policy caps permissions independently of booleans',()=>{const s=spec(),r=computeReview(s);const record={schemaVersion:2,id:r.id,createdAt:new Date().toISOString(),rationale:'Test',nextReview:'2027-01-02',a:s.a,b:s.b,manifest:{...s.dataset.manifest,retention:'operation',policy:'tiingo-byok'},result:r,settings:{frequency:s.frequency,costBps:s.costBps,initialNav:s.initialNav,cashReturnConfirmed:true,partialCoverageConfirmed:false}};expect(()=>validateRecord(record)).toThrow(/calculation-only/);});
});
